### ISSUE TITLE
Lazily fetch code

### ISSUE THREAD

**Issue by t-mullen** [multihack/multihack-web#33]
Instead of fetching all of the code, the user should be able to:

- [ ] See the entire directory structure on joining.
- [ ] Fetch individual files when opening them.
- [ ] Still have the option to fetch the whole project.

**Comment by kifhan** [comment]
I really appreciate your code and it inspired me. But it seems you don't understand a concept.
Please check this carefully.
[Collaborative-editing-javascript-intro-operational-transformation](https://davidwalsh.name/collaborative-editing-javascript-intro-operational-transformation)

This show you how to sync shared filesystem without fetching all the project files. You may ignore a webtorrent part.
[Shared Filesystem with Y-js](http://y-js.org/shared-filesystem/components/shared-filesystem/demo/#vnynil)

I concern this issue because I'm working on the project something like this. Maybe I can share some of my code later.
Thank you.

**Comment by t-mullen** [comment]
Interesting article, I didn't know about this.

I'll definitely see if I can use this method instead. Thanks.

We will still need to lazily load files though. Most projects are simply too large to send entirely, regardless of the method.

**Comment by t-mullen** [comment]
Closing this in favour of simply sending the whole project at startup.

It's less confusing than the "Fetch Code at startup" plan, and I think the protocol handles things well enough. Big projects will have to set an option to skip this.

**Comment by kifhan** [comment]
What about fetching project file using CRDT?
Make dictionary type (key, value) of object to use it as an abstraction of file system and sync it by CRDT. Sync a exact file when change detected.

**Comment by t-mullen** [comment]
Yes, this will need to be done when implementing #34 

This issue was just for fetching files when opening them, but it doesn't seem like there will be a need for it.
